//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Architectural overview and usage guide: 
// http://blogofrab.blogspot.com/2010/08/maintenance-free-mocking-for-unit.html
//------------------------------------------------------------------------------
using System.Data.EntityClient;
using System.Data.Objects;

namespace PRSErrorMonitor
{
    /// <summary>
    /// The functional concrete object context. This is just like the normal
    /// context that would be generated using the POCO artefact generator, 
    /// apart from the fact that this one implements an interface containing 
    /// the entity set properties and exposes <code>IObjectSet</code>
    /// instances for entity set properties.
    /// </summary>
    public partial class ReportingEntities : ObjectContext, IReportingEntities 
    {
        public const string ConnectionString = "name=ReportingEntities";
        public const string ContainerName = "ReportingEntities";
    
        #region Constructors
    
        public ReportingEntities():
            base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ReportingEntities(string connectionString):
            base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ReportingEntities(EntityConnection connection):
            base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public IObjectSet<tbPRSErrorMonitor> tbPRSErrorMonitor
        {
            get { return _tbPRSErrorMonitor ?? (_tbPRSErrorMonitor = CreateObjectSet<tbPRSErrorMonitor>("tbPRSErrorMonitor")); }
        }
        private ObjectSet<tbPRSErrorMonitor> _tbPRSErrorMonitor;

        #endregion
    }
}
